data:
  train_urls:
    - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_train.{1..128}-of-128.jsonl.gz"
  validation_urls:
    - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_val.{1..8}-of-8.jsonl.gz"
  cache_dir: "gs://levanter-data-new/tokenized/openwebtext_llama/"
  tokenizer: "meta-llama/Llama-2-70b-hf"
model:
  type: llama
  hidden_dim: 2304
  num_heads: 12
  num_layers: 12
  seq_len: 16384
  num_heads: 12
  gradient_checkpointing: True

trainer:
  wandb:
    project: "levanter-new"
    tags: ["openwebtext", "llama_100m"]
  mp: p=f32,c=bfloat16
  train_batch_size: 1024
  num_train_steps: 100000
  steps_per_eval: 500